server:
  port: 8090
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/test
    username:root
    password:root
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.duyi.model
